<?php
/***************************************************************************
 * storage/psql.inc
 *               PostgeSQL storage driver
 *
 * authors:      Alexander Meindl <am@meindlsoft.com>
 *               Sven Reul <heffer@quaddamage.de>
 *			     Scotti ???	
 *
 *               Released under v2 of the GNU LGPL
 *
 * $Id: psql.inc,v 1.1 2004/06/22 19:07:19 mr3dblond Exp $
 **************************************************************************/

class phpmailapi_storage extends phpmailapi_imap
{

}

?>
